# Generated by Django 3.1.2 on 2020-10-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20201020_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
    ]
