# Generated by Django 3.1.2 on 2020-10-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20201020_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
    ]
