# Generated by Django 3.1.2 on 2020-10-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20201022_0436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={},
        ),
    ]
