# Generated by Django 3.1.2 on 2020-10-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_auto_20201025_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default=None, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
