# Generated by Django 3.1.4 on 2020-12-28 10:02

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_auto_20201228_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(help_text='Image of your restaurant', null=True, upload_to=restaurants.models.upload_to),
        ),
    ]
