# Generated by Django 3.1.4 on 2020-12-28 20:09

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_auto_20201228_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, help_text='An image or logo for your restaurant (optional)', null=True, upload_to=restaurants.models.upload_to),
        ),
    ]
