# Generated by Django 3.1.4 on 2020-12-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_squashed_0018_auto_20201228_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
