# Generated by Django 3.1.4 on 2020-12-29 03:17

from django.db import migrations, models
import django.db.models.deletion
import menus.models


class Migration(migrations.Migration):

    replaces = [('menus', '0001_initial'), ('menus', '0002_auto_20201020_1830'), ('menus', '0003_auto_20201020_2046'), ('menus', '0004_remove_menusection_image'), ('menus', '0005_auto_20201022_0443'), ('menus', '0006_auto_20201025_0053'), ('menus', '0007_auto_20201025_2114'), ('menus', '0008_menuitem'), ('menus', '0009_auto_20201025_2123'), ('menus', '0010_auto_20201025_2127'), ('menus', '0011_auto_20201030_0631'), ('menus', '0012_menu_image'), ('menus', '0013_menuitem_price'), ('menus', '0014_auto_20201228_2152'), ('menus', '0015_auto_20201229_0312'), ('menus', '0016_auto_20201229_0314')]

    initial = True

    dependencies = [
        ('restaurants', '0002_auto_20201020_2046'),
        ('restaurants', '0014_auto_20201025_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128)),
                ('theme', models.CharField(choices=[('default', 'Default'), ('secondary', 'Secondary')], default='default', max_length=32)),
                ('restaurant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
                ('slug', models.SlugField(default=None, max_length=128)),
                ('image', models.ImageField(blank=True, help_text='An image or logo for this menu (optional)', null=True, upload_to=menus.models.menu_upload_to)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu')),
                ('name', models.CharField(default=None, max_length=128)),
                ('slug', models.SlugField(default=None, max_length=128)),
                ('image', models.ImageField(blank=True, help_text='An image or logo for this section (optional)', null=True, upload_to=menus.models.menusection_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128)),
                ('description', models.CharField(blank=True, default=None, max_length=1024)),
                ('slug', models.SlugField(max_length=128)),
                ('menusection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menusection')),
                ('price', models.IntegerField(blank=True, help_text='Enter the price in cents (e.g. $5.00 = 500 cents)', null=True)),
            ],
        ),
    ]
