# Generated by Django 3.1.4 on 2020-12-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menusection_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusection',
            name='notes',
        ),
    ]
