# Generated by Django 3.1.4 on 2020-12-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20201229_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusection',
            name='note',
            field=models.CharField(blank=True, help_text="An optional note about this section (e.g. 'Drinks come with complimentary refills.')", max_length=256, null=True),
        ),
    ]
