#!/bin/bash

secret_key_path="$(dirname "$0")/secret_key.py"

if [ ! -f $secret_key_path ]; then
  echo "Generating new SECRET_KEY..."
  echo "SECRET_KEY = '$(openssl rand -hex 32)'" > $secret_key_path
else
  echo "SECRET_KEY already exists. Moving on..."
fi
