#!/bin/bash

app_location=$(dirname "$0")
config_file_name="server_config.py"

if [ "$1" != "dev" ] && [ "$1" != "test" ] && [ "$1" != "prod" ]; then
  echo ""
  echo "First argument must be one of: dev, test, prod"
  echo "For example: '$app_location/$(basename "$0") dev'"
  exit 1
fi

echo "Using '$1' settings for '$config_file_name'..."
cp $app_location/server_config.$1.py $app_location/$config_file_name
