# Generated by Django 3.1.2 on 2020-10-20 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20201020_2046'),
        ('menus', '0002_auto_20201020_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='menusection',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='menusection',
            name='slug',
            field=models.SlugField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
