# Generated by Django 3.1.4 on 2020-12-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20201229_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusection',
            name='notes',
            field=models.JSONField(default={}),
        ),
    ]
