# Generated by Django 3.1.2 on 2020-10-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20201020_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusection',
            name='image',
        ),
    ]
