# Generated by Django 3.1.2 on 2020-10-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_remove_menusection_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name']},
        ),
    ]
