# Generated by Django 3.1.2 on 2020-10-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_auto_20201022_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='menusection',
            name='name',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
