# Generated by Django 3.1.2 on 2020-10-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_auto_20201025_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128)),
                ('description', models.CharField(default=None, max_length=1024)),
                ('slug', models.SlugField(max_length=128)),
                ('menusection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menusection')),
            ],
        ),
    ]
