# Generated by Django 3.1.2 on 2020-10-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
