# Generated by Django 3.1.2 on 2020-10-30 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_auto_20201025_2114'),
        ('menus', '0010_auto_20201025_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
            preserve_default=False,
        ),
    ]
