# Generated by Django 3.1.4 on 2020-12-28 21:33

from django.db import migrations, models
import menus.models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_auto_20201030_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, help_text='An image or logo for this menu (optional)', null=True, upload_to=menus.models.upload_to),
        ),
    ]
