# Generated by Django 3.1.4 on 2020-12-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0012_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
