# Generated by Django 3.1.4 on 2020-12-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0013_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(blank=True, help_text='Enter the price in cents (e.g. $5.00 = 500 cents)', null=True),
        ),
    ]
