# Generated by Django 3.1.4 on 2020-12-29 03:14

from django.db import migrations, models
import menus.models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0015_auto_20201229_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.AlterField(
            model_name='menusection',
            name='image',
            field=models.ImageField(blank=True, help_text='An image or logo for this section (optional)', null=True, upload_to=menus.models.menusection_upload_to),
        ),
    ]
